(quote $expr)
(defmacro! $symbol $params $body)
(lambda $params $body)
(let! $symbol $expr)
(set! $symbol $expr)
(define! $symbol $expr)
(if $expr $expr)
(if $expr $expr $expr)
(for $symbol $exp $body)
(do $body)
(ref $expr $expr)
(ref-set $expr $expr)